/**
 * Fetches the OpenAPI spec from the Chatterbox TTS API and generates TypeScript types.
 *
 * Usage:
 * CHATTERBOX_API_URL=https://your-api-url bun run sync-api.ts
 *
 * Or with .env file:
 * bun run sync-api.ts
 */

import path from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

// 1. Get the API URL from the environment (Bun loads .env automatically)
const apiUrl = process.env.CHATTERBOX_API_URL;
if (!apiUrl) {
  console.error("Error: CHATTERBOX_API_URL environment variable is required");
  process.exit(1);
}

const openApiUrl = `${apiUrl}/openapi.json`;
console.log(`Fetching OpenAPI spec from: ${openApiUrl}`);

// 2. Fetch and parse the OpenAPI spec (Top-level await is native)
const ast = await openapiTS(new URL(openApiUrl));
const contents = astToString(ast);

// 3. Prepare output path (import.meta.dir replaces __dirname)
const outputPath = path.resolve(import.meta.dir, "../src/types/chatterbox-api.d.ts");

// 4. Construct the file content
const header = `/**
 * This file is auto-generated by scripts/sync-api.ts
 * Do not edit manually. Run \`bun run sync-api.ts\` to regenerate.
 *
 * Generated from: ${openApiUrl}
 * Generated at: ${new Date().toISOString()}
 */\n\n`;

// 5. Write the file (Bun.write automatically creates missing directories)
await Bun.write(outputPath, header + contents);

console.log(`Types written to: ${outputPath}`);